@echo off
del /Q %~dp0export_Organizations\read\*.csv 2>NUL
del /Q %~dp0export_Organizations\log\*.csv 2>NUL
del /Q %~dp0export_Organizations\write\*.csv 2>NUL
copy /Y nul %~dp0export_Organizations\log\sdl.log
del /Q %~dp0export_Users\read\*.csv 2>NUL
del /Q %~dp0export_Users\log\*.csv 2>NUL
del /Q %~dp0export_Users\write\*.csv 2>NUL
copy /Y nul %~dp0export_Users\log\sdl.log
del /Q %~dp0export_Projects\read\*.csv 2>NUL
del /Q %~dp0export_Projects\log\*.csv 2>NUL
del /Q %~dp0export_Projects\write\*.csv 2>NUL
copy /Y nul %~dp0export_Projects\log\sdl.log
del /Q %~dp0export_Projectbudgetlines\read\*.csv 2>NUL
del /Q %~dp0export_Projectbudgetlines\log\*.csv 2>NUL
del /Q %~dp0export_Projectbudgetlines\write\*.csv 2>NUL
copy /Y nul %~dp0export_Projectbudgetlines\log\sdl.log
del /Q %~dp0export_Donations\read\*.csv 2>NUL
del /Q %~dp0export_Donations\log\*.csv 2>NUL
del /Q %~dp0export_Donations\write\*.csv 2>NUL
copy /Y nul %~dp0export_Donations\log\sdl.log
del /Q %~dp0export_Tasks\read\*.csv 2>NUL
del /Q %~dp0export_Tasks\log\*.csv 2>NUL
del /Q %~dp0export_Tasks\write\*.csv 2>NUL
copy /Y nul %~dp0export_Tasks\log\sdl.log
del /Q %~dp0export_Taskmembers\read\*.csv 2>NUL
del /Q %~dp0export_Taskmembers\log\*.csv 2>NUL
del /Q %~dp0export_Taskmembers\write\*.csv 2>NUL
copy /Y nul %~dp0export_Taskmembers\log\sdl.log
del /Q %~dp0export_Vouchers\read\*.csv 2>NUL
del /Q %~dp0export_Vouchers\log\*.csv 2>NUL
del /Q %~dp0export_Vouchers\write\*.csv 2>NUL
copy /Y nul %~dp0export_Vouchers\log\sdl.log